@startuml Sequenzdiagramm FA01
title Sequenzdiagramm – FA01 Projektarbeitsbereich erstellen (Normalablauf)

actor Projektmanager as PM
participant "ConsoleClient" as UI
participant ":IVorlagenService" as VSVC
participant ":IArbeitsbereichService" as SVC
participant ":ProjektarbeitsbereichFactory" as FAC
participant ":IProjektarbeitsbereichRepository" as REPO
participant ":IDataAccess" as DA

PM -> UI : Arbeitsbereich erstellen
activate UI

UI -> VSVC : vorlagenLaden()
activate VSVC
VSVC --> UI : List<Projektvorlage>
deactivate VSVC

UI -> SVC : arbeitsbereichErstellen(name, vorlageId)
activate SVC

SVC -> VSVC : vorlageFinden(vorlageId)
activate VSVC
VSVC --> SVC : projektvorlage
deactivate VSVC

SVC -> FAC : getInstance()
activate FAC
FAC --> SVC : factory
SVC -> FAC : erstelle(name, projektvorlage)
FAC --> SVC : projektarbeitsbereich
deactivate FAC

SVC -> REPO : save(projektarbeitsbereich)
activate REPO
REPO -> DA : create("Projektarbeitsbereich", data)
activate DA
DA --> REPO : neueId
deactivate DA
REPO --> SVC : gespeicherterArbeitsbereich
deactivate REPO

SVC --> UI : projektarbeitsbereich
deactivate SVC

UI --> PM : Bestätigung + URL
deactivate UI

@enduml
